CONFIG += c++14

isEmpty(PARENT_BUILD_DIR) : PARENT_BUILD_DIR = $$OUT_PWD

MOC_DIR      = $$PARENT_BUILD_DIR/$$TARGET
OBJECTS_DIR  = $$PARENT_BUILD_DIR/$$TARGET
RCC_DIR      = $$PARENT_BUILD_DIR/$$TARGET
UI_DIR       = $$PARENT_BUILD_DIR/$$TARGET

CONFIG(debug  , debug|release) : BUILD_TYPE=debug
CONFIG(release, debug|release) : BUILD_TYPE=release

DESTDIR     = $$PARENT_BUILD_DIR/$$BUILD_TYPE

LIBS       *= -L$$PARENT_BUILD_DIR/$$BUILD_TYPE
